
import java.awt.Font;
import java.awt.Graphics2D;
import javax.swing.*;
import java.awt.*;
import java.awt.geom.*;

public class graphics extends javax.swing.JFrame {

    
    public graphics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 800));

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("jRadioButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(554, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jRadioButton1)
                .addGap(34, 34, 34)
                .addComponent(jRadioButton2)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        int xPonts[]={55,267,109,73,83,55,27,237,1,43};
        int yPonts[]={0,236,36,54,96,72,96,254,36,36};
        Graphics2D q =(Graphics2D) getGraphics();
        Graphics2D q2 =(Graphics2D) getGraphics();
        Graphics2D q3 =(Graphics2D) getGraphics();
        Graphics2D q4 =(Graphics2D) getGraphics();

        GeneralPath star = new GeneralPath();
        star.moveTo(xPonts[0],yPonts[0]);
        
        for(int k = 1;k<xPonts.length;k++)
            star.lineTo(xPonts[k], yPonts[k]);
        star.closePath();
        q.translate(200, 200);
        q2.translate(800, 200);
        q3.translate(800, 500);
        q4.translate(200, 500);
        for(int j = 1; j<=20;j++)
        {
        q.rotate(Math.PI/10.0);
        q.setColor(
        new Color((int) (Math.random()*256),
        (int) (Math.random()*256),
        (int) (Math.random()*256)));
        
        q.fill(star);
        
         q2.rotate(Math.PI/10.0);
        q2.setColor(
        new Color((int) (Math.random()*256),
        (int) (Math.random()*256),
        (int) (Math.random()*256)));
        
        q2.fill(star);
        
         q3.rotate(Math.PI/10.0);
        q3.setColor(
        new Color((int) (Math.random()*256),
        (int) (Math.random()*256),
        (int) (Math.random()*256)));
        
        q3.fill(star);
        
         q4.rotate(Math.PI/5.0);
        q4.setColor(
        new Color((int) (Math.random()*256),
        (int) (Math.random()*256),
        (int) (Math.random()*256)));
        
        q4.fill(star);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
